# -*- coding: utf-8 -*-
"""Resumechecking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmLHk251Wg8D5Y2IYKrrX9NbHu-0Iz4v
"""

!pip install -U langchain_xai
!pip install langchain_community
!pip install pypdf
!pip install langchain_core
!pip install langchain_groq
!pip install -U sentence_transformers

import os

os.environ['GROQ_API_KEY']="GROQ_API_KEY"

from langchain_groq import ChatGroq

chat = ChatGroq(
    model='meta-llama/llama-4-scout-17b-16e-instruct',
    api_key="GROQ_API_KEY"
)
result = chat.invoke("Who is Roger Federer, answer in two lines")
print(result.content)

"""PDF Based checker

"""

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("/content/sushi_resume (1).pdf")
documents = loader.load()

context = "\n\n".join(doc.page_content for doc in documents)

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["context", "experience_level", "level_note"],
    template="""
You are a senior technical recruiter and career coach with 15 years of experience across FAANG, startups, and consulting.
You evaluate resumes for {experience_level}-level candidates with the mindset of a hiring manager reviewing 200 applications per week.

DETECTED EXPERIENCE LEVEL: {experience_level}
EVALUATION CONTEXT: {level_note}

RESUME CONTENT:
{context}

-------------------------
SCORING RUBRIC (100 points total):
-------------------------

1. Content Quality (0-20)
   - Relevance and clarity of experience/projects
   - For freshers: coursework and academic context counts

2. Skills & Technical Depth (0-20)
   - Actual depth vs. keyword stuffing
   - Penalize listing tools without context of usage

3. Structure & Formatting (0-15)
   - ATS parse-friendly layout
   - No tables, columns, or graphics (they break parsers)

4. Impact & Achievements (0-20)
   - Quantified results (%, $, time saved, scale)
   - Action-verb lead sentences (built, designed, reduced, led)

5. ATS Optimization (0-15)
   - Relevant keywords for the detected domain
   - Parsing-safe formatting

6. Projects & Practical Work (0-10)
   - Complexity, real-world applicability
   - GitHub/live links add points

-------------------------
IMPORTANT RULES:
-------------------------
- Be critical, not polite
- Do not inflate scores
- overall_score must equal the exact sum of all category_scores
- Penalize vague or generic resumes heavily
- Keep suggestions actionable, not generic
- If something is missing, explicitly call it out

-------------------------
OUTPUT FORMAT (STRICT JSON ONLY):
-------------------------
Return ONLY valid JSON. Zero prose outside JSON.

{{
  "overall_score": integer,
  "experience_level": "fresher | mid | senior",
  "ats_score_label": "poor | fair | good | excellent",
  "category_scores": {{
    "content_quality": integer,
    "skills_depth": integer,
    "structure_formatting": integer,
    "impact_achievements": integer,
    "ats_optimization": integer,
    "projects": integer
  }},
  "strengths": ["point 1", "point 2", "point 3"],
  "weaknesses": ["point 1", "point 2", "point 3"],
  "detected_skills": ["skill 1", "skill 2"],
  "missing_skills": ["skill 1", "skill 2"],
  "next_roles": ["role 1", "role 2"],
  "improvement_suggestions": ["actionable fix 1", "actionable fix 2"]
}}
"""
)

# detect level
def detect_level(text: str) -> str:
    t = text.lower()
    if any(s in t for s in ["staff", "principal", "director", "vp ", "8+ years", "10+ years"]):
        return "senior"
    if any(s in t for s in ["2 years", "3 years", "4 years", "senior", "lead"]):
        return "mid"
    return "fresher"

RUBRIC_WEIGHTS = {
    "fresher": "No work experience expected. Weight projects, skills, and academics heavily. Do NOT penalize for missing industry experience.",
    "mid": "1-4 years expected. Balance experience quality with skills and impact. Penalize vague role descriptions.",
    "senior": "5+ years expected. Weight leadership, system design, measurable impact, and strategic thinking heavily.",
}

experience_level = detect_level(context)
level_note = RUBRIC_WEIGHTS[experience_level]
formatted_prompt = prompt.format(context=context, experience_level=experience_level, level_note=level_note)

for m in chat.stream(formatted_prompt):
  print(m.content, end="", flush=True)

!git init
!git config --global user.email "pakrashys@gmail.com"
!git config --global user.name "Sushit-prog"

# Commented out IPython magic to ensure Python compatibility.
# clone instead of starting from scratch
!git clone https://github.com/username/repo.git
# %cd repo

# copy your files into this folder

!git add .
!git commit -m "update from colab"
!git push

